[reqad]
template=nginx_php-fpm
#template=apache_modphp
email=1
quota=0
accounts=100
wptoolkit=1
backup=1
backupdb=0
terminal=1
transfer=1
root_access=1
filemanager=1
wireguard=1

[web]
php_versions=7.4, 8.2, 8.3, 8.4, 8.5
php=7.4
nginx=1.30
mariaddb=10.6

[systemd]
services=crond, dovecot, exim, lfd, mariadb, monit, nginx, pdns, php-fpm, php82-php-fpm, php83-php-fpm, php84-php-fpm, php85-php-fpm, redis, reqad, spamassassin, sshd, vnstat, reqad-php-fpm
timers=certbot-renew, dnf-automatic, fstrim, sysstat-collect, sysstat-summary

