#!/opt/reqad/php-current/usr/bin/php -c/etc/reqad/php-fpm/php.ini
<?php
/**
 * Reqad — import_cpanel_autoresponders.php
 *
 * Import a cPanel account's autoresponders. The transfer tool pulls the
 * directory; this turns it into Reqad autoresponders.
 *
 *   cPanel path                          what it holds
 *   /home/<acct>/.autorespond/<addr>       From/Content-type/Subject + body
 *   /home/<acct>/.autorespond/<addr>.json  {"start":…,"stop":…,"interval":…}
 *
 * start / stop are unix timestamps, or null for "no bound". The pair is the
 * schedule: the responder is live when now is inside it. Reqad schedules by
 * DAY (date_from / date_to), so a stop at 23:59 becomes that whole date — the
 * import can leave a responder live for a few hours longer than cPanel would,
 * never for a day less. `interval` (cPanel's resend suppression) has no Reqad
 * equivalent: vacation is pinned to :days 1, so a non-default one is reported
 * and dropped rather than silently honoured as something else.
 *
 * MAILBOXES ARE CREATED WHEN MISSING. On cPanel an autoresponder is a pipe
 * alias in /etc/valiases and needs no mailbox — that is how a departed
 * employee's address keeps answering after the account is gone. Reqad's
 * autoresponder is a Pigeonhole vacation script that only runs when dovecot
 * LMTP delivers to a mailbox, so an import with no mailbox would be a row that
 * never fires. Such an address gets a mailbox with a random password, printed
 * here; --no-create skips those addresses instead.
 *
 * DRY RUN BY DEFAULT. Nothing is written without --apply, because this creates
 * mailboxes and starts replying to strangers on the sender's behalf.
 *
 * Usage:
 *   import_cpanel_autoresponders.php --domain=D --dir=DIR [--apply]
 *                                    [--replace] [--include-expired] [--no-create]
 *
 * --replace overwrites autoresponders that already exist here; without it they
 * are left alone, so a re-run is safe. --include-expired also imports the ones
 * whose window has already closed (they import as inactive, for the record).
 *
 * The shebang pins Reqad's own php.ini: the stock CLI ini disables exec(),
 * which ef_helper() needs to reach the privileged Sieve helper.
 */

require_once '/usr/local/reqad/public_html/defines.php';
require_once '/usr/local/reqad/public_html/modules/functions.php';

$opt   = getopt('', array('domain:', 'dir:', 'apply', 'replace', 'include-expired', 'no-create', 'help'));
$usage = "usage: import_cpanel_autoresponders.php --domain=<domain> --dir=<staged .autorespond dir>"
       . " [--apply] [--replace] [--include-expired] [--no-create]\n";

if (isset($opt['help']) || !isset($opt['domain']) || !isset($opt['dir']))
    exit($usage);

$domain   = strtolower(trim((string)$opt['domain']));
$dir      = rtrim((string)$opt['dir'], '/');
$apply    = isset($opt['apply']);
$replace  = isset($opt['replace']);
$expired_too = isset($opt['include-expired']);
$no_create   = isset($opt['no-create']);

if (!valid_domain($domain))
    exit("ERROR: --domain must be a domain name\n");
if (!is_dir($dir) || !is_readable($dir))
    exit("ERROR: cannot read directory $dir\n");

$today = date('Y-m-d');
$now   = time();

/* One cPanel .autorespond directory serves every domain on the account, and the
   transfer tool moves one domain at a time, so everything else is skipped. */
$files = array();
foreach (scandir($dir) as $f) {
    if ($f === '.' || $f === '..' || substr($f, -5) === '.json' || $f === 'info_log')
        continue;
    if (!is_file($dir . '/' . $f))
        continue;
    $addr = strtolower($f);
    $at   = strrpos($addr, '@');
    if ($at === false || substr($addr, $at + 1) !== $domain)
        continue;
    $lp = substr($addr, 0, $at);
    if (!valid_email_user($lp))
        continue;
    $files[$lp] = $dir . '/' . $f;
}
ksort($files);

if (!$files)
    exit("No autoresponders for $domain in $dir\n");

/* Parse the cPanel message file: RFC-822-ish headers, blank line, body. Only
   Subject and the Content-type charset matter here — From is regenerated by
   Reqad from the mailbox, and the rest is cPanel's own bookkeeping. */
function ar_parse_message($raw) {
    $raw   = str_replace("\r\n", "\n", (string)$raw);
    $split = strpos($raw, "\n\n");
    if ($split === false) {
        $head = $raw;
        $body = '';
    } else {
        $head = substr($raw, 0, $split);
        $body = substr($raw, $split + 2);
    }

    $subject = '';
    $charset = '';
    $other   = array();
    foreach (explode("\n", $head) as $line) {
        if (!preg_match('/^([A-Za-z\-]+):\s*(.*)$/', $line, $m)) {
            /* Not a header at all: the file has no header block, so the whole
               thing is the body. */
            return array('subject' => '', 'body' => $raw, 'charset' => '', 'other' => array());
        }
        $name = strtolower($m[1]);
        $val  = trim($m[2]);
        if ($name === 'subject')
            $subject = $val;
        else if ($name === 'content-type') {
            if (preg_match('/charset\s*=\s*"?([A-Za-z0-9_\-\.:]+)"?/i', $val, $c))
                $charset = strtolower($c[1]);
        } else if ($name !== 'from')
            $other[] = $m[1] . ': ' . $val;
    }

    return array('subject' => $subject, 'body' => $body, 'charset' => $charset, 'other' => $other);
}

/* cPanel writes the message in whatever charset the mail client used — the
   panel stores UTF-8 and Pigeonhole re-encodes from it, so anything else is
   converted here. An unknown charset is left alone rather than mangled. */
function ar_to_utf8($text, $charset) {
    if ($text === '' || $charset === '' || $charset === 'utf-8' || $charset === 'utf8')
        return array($text, '');
    $conv = @iconv($charset, 'UTF-8//TRANSLIT', $text);
    if ($conv === false || $conv === null)
        return array($text, "unknown charset '$charset', text kept as-is");
    return array($conv, '');
}

printf("%s → domain %s\n", $dir, $domain);
printf("  %d autoresponder file(s) for this domain\n\n", count($files));

$plan = array();
foreach ($files as $lp => $path) {
    $addr = $lp . '@' . $domain;
    $msg  = ar_parse_message(file_get_contents($path));

    $json  = array();
    if (is_readable($path . '.json'))
        $json = (array)json_decode(file_get_contents($path . '.json'), true);
    $start = isset($json['start']) && $json['start'] !== null ? (int)$json['start'] : 0;
    $stop  = isset($json['stop'])  && $json['stop']  !== null ? (int)$json['stop']  : 0;
    $interval = isset($json['interval']) ? (int)$json['interval'] : 0;

    $state = 'active';
    if ($stop && $stop <= $now)         $state = 'expired';
    else if ($start && $start > $now)   $state = 'scheduled';

    list($subject, $warn_s) = ar_to_utf8($msg['subject'], $msg['charset']);
    list($body,    $warn_b) = ar_to_utf8($msg['body'],    $msg['charset']);

    $notes = array();
    if ($warn_s || $warn_b)      $notes[] = $warn_s ? $warn_s : $warn_b;
    if ($msg['other'])           $notes[] = 'headers not carried over: ' . implode(', ', $msg['other']);
    if ($interval > 0)           $notes[] = "cPanel interval $interval dropped — Reqad replies at most once a day per sender";
    if (stripos($subject . $body, '%subject%') !== false)
        $notes[] = 'uses %subject%, which Reqad supports';
    if (preg_match('/%(from|email|to|day|month|year)%/i', $subject . $body, $ph))
        $notes[] = "contains {$ph[0]}, which Reqad does NOT expand — it stays literal";

    printf("  %-9s %s\n", strtoupper($state), $addr);
    printf("            subject: %s\n", $subject !== '' ? $subject : '(none)');
    printf("            window : %s → %s\n",
           $start ? date('Y-m-d H:i', $start) : 'always',
           $stop  ? date('Y-m-d H:i', $stop)  : 'never');
    if (!mailbox_exists($lp, $domain))
        printf("            mailbox: does not exist%s\n",
               $no_create ? ' — SKIPPED (--no-create)' : ' — will be created');
    foreach ($notes as $n)
        printf("            note   : %s\n", $n);

    if ($subject === '' && trim($body) === '') {
        print "            SKIPPED — empty subject and body, nothing to send.\n\n";
        continue;
    }
    if ($state === 'expired' && !$expired_too) {
        print "            SKIPPED — the window closed already (--include-expired to take it anyway).\n\n";
        continue;
    }
    if ($no_create && !mailbox_exists($lp, $domain)) {
        print "\n";
        continue;
    }

    /* An address with no subject would send a Subject-less auto-reply; cPanel's
       own default is what the admin saw in the old panel, so keep it visible. */
    if ($subject === '')
        $subject = 'Out of office';

    $plan[] = array(
        'lp'        => $lp,
        'subject'   => $subject,
        'message'   => rtrim($body, "\n"),
        'date_from' => $start ? date('Y-m-d', $start) : '',
        'date_to'   => $stop  ? date('Y-m-d', $stop)  : '',
        'state'     => $state,
    );
    print "\n";
}

if (!$plan)
    exit("Nothing to import.\n");

/* What is already here. A plain re-run must not clobber an autoresponder the
   admin has since edited on this server. */
$existing = array();
$res = $db->query('SELECT user FROM autoresponders WHERE domain = ' . "'" . SQLite3::escapeString($domain) . "'");
while ($row = $res->fetchArray(SQLITE3_ASSOC))
    $existing[strtolower($row['user'])] = true;

$todo = array();
foreach ($plan as $p) {
    if (isset($existing[$p['lp']]) && !$replace) {
        printf("  ALREADY HERE  %s@%s — left untouched (--replace to overwrite)\n", $p['lp'], $domain);
        continue;
    }
    $todo[] = $p;
}
if (!$todo)
    exit("\nNothing left to import.\n");

printf("\n  Result: %d autoresponder(s) to import.\n", count($todo));

if (!$apply)
    exit("\nDry run — nothing written. Re-run with --apply to import.\n");

$imported = 0;
$failed   = 0;
foreach ($todo as $p) {
    $lp   = $p['lp'];
    $addr = $lp . '@' . $domain;

    if (!mailbox_exists($lp, $domain)) {
        $pass = mailbox_random_password();
        $err  = mailbox_create($lp, $domain, $pass);
        if ($err !== '') {
            printf("  FAILED  %s — mailbox not created: %s\n", $addr, $err);
            $failed++;
            continue;
        }
        printf("  MAILBOX %s created, password: %s\n", $addr, $pass);
    }

    $st = $db->prepare('INSERT OR REPLACE INTO autoresponders (user, domain, subject, message, date_from, date_to)'
                     . ' VALUES (:u, :d, :s, :m, :df, :dt)');
    $st->bindValue(':u',  $lp,             SQLITE3_TEXT);
    $st->bindValue(':d',  $domain,         SQLITE3_TEXT);
    $st->bindValue(':s',  $p['subject'],   SQLITE3_TEXT);
    $st->bindValue(':m',  $p['message'],   SQLITE3_TEXT);
    $st->bindValue(':df', $p['date_from'], SQLITE3_TEXT);
    $st->bindValue(':dt', $p['date_to'],   SQLITE3_TEXT);
    $st->execute();

    /* Same rule the panel and the 5-minute cron use, so an imported responder
       is live immediately if its window says so instead of waiting for the
       next cron run. One outside its window is left as a row only. */
    $live = ($p['date_from'] === '' || $p['date_from'] <= $today)
         && ($p['date_to']   === '' || $p['date_to']   >= $today);

    if ($live) {
        $err = autoresponder_apply($lp, $domain, $p['subject'], $p['message']);
        if ($err !== '') {
            printf("  FAILED  %s — imported, but the sieve script was not written: %s\n", $addr, $err);
            $failed++;
            continue;
        }
        printf("  IMPORTED %s — active now\n", $addr);
    } else {
        printf("  IMPORTED %s — inactive (%s)\n", $addr, $p['state']);
    }
    $imported++;
}

printf("\nImported %d autoresponder(s) for %s%s.\n", $imported, $domain,
       $failed ? ", $failed failed" : '');
