#!/bin/bash
#
# seed_skiprbl_extra.sh -- one-shot migration for /etc/exim/skiprblhosts
#
# The pre-1.0.28 file was hand-maintained: a flat list of addresses with no
# record of which were well-known ESP ranges and which the operator had added
# themselves. build-skiprbl.sh regenerates the ESP part from SPF, so the only
# thing worth rescuing is the rest -- and "the rest" has to be worked out,
# because the file does not say.
#
# Each old address is offered to exim against a freshly generated list. Exim
# owns the containment rules for this file format, so asking it is the only
# answer that agrees with what the running server will actually do. Whatever
# no provider covers is stored as the panel's extra addresses.
#
# Safe to re-run: it does nothing once skiprbl-extra exists, or once the file
# on disk is already a generated one.
#
# Reqad -- https://www.reqad.com/

set -u
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH

REQAD=/usr/local/reqad
DB="$REQAD/db/reqad.db"
SQLITE=/usr/bin/sqlite3
LIVE=/etc/exim/skiprblhosts
BUILDER="$REQAD/scripts/mail/build-skiprbl.sh"

[ -r "$LIVE" ]     || { echo "seed_skiprbl_extra: no $LIVE, nothing to migrate"; exit 0; }
[ -x "$BUILDER" ]  || { echo "seed_skiprbl_extra: $BUILDER missing" >&2; exit 1; }
[ -r "$DB" ]       || { echo "seed_skiprbl_extra: no panel database" >&2; exit 1; }
[ -x "$SQLITE" ]   || { echo "seed_skiprbl_extra: $SQLITE missing" >&2; exit 1; }

# already generated by us -> there is nothing hand-written left to rescue
if grep -q '^#  esp-entries:' "$LIVE"; then
	echo "seed_skiprbl_extra: $LIVE is already generated, skipping"
	exit 0
fi

have=$("$SQLITE" -init /dev/null -batch -noheader -list "$DB" \
       "SELECT count(*) FROM settings WHERE name='skiprbl-extra';" 2>/dev/null)
if [ "${have:-0}" != "0" ]; then
	echo "seed_skiprbl_extra: skiprbl-extra already set, skipping"
	exit 0
fi

TMP=$(mktemp -d /tmp/skiprblseed.XXXXXX) || exit 1
trap 'rm -rf "$TMP"' EXIT

GEN="$TMP/generated"
if ! "$BUILDER" --dry-run --quiet > "$GEN" 2>"$TMP/err"; then
	echo "seed_skiprbl_extra: could not generate a provider list, leaving $LIVE alone" >&2
	sed 's/^/  /' "$TMP/err" >&2
	exit 1
fi
chmod 644 "$GEN"
if ! grep -q '^#  esp-entries:' "$GEN"; then
	echo "seed_skiprbl_extra: generated list looks wrong, aborting" >&2
	exit 1
fi

cp -a "$LIVE" "$LIVE.pre-reqad.$(date +%Y%m%d%H%M%S)"

KEEP="$TMP/keep"
: > "$KEEP"
kept=0; covered=0; bad=0

while IFS= read -r line; do
	line=${line%$'\r'}
	addr=${line%%#*}
	note=''
	[ "$line" != "$addr" ] && note=${line#*#}
	addr=$(echo "$addr" | tr -d ' \t')
	case "$addr" in ''|'#'*) continue ;; esac

	# exim decides containment, using the same list syntax it will serve
	probe=${addr%%/*}
	if [ "$(exim -be "\${if match_ip{$probe}{$GEN}{Y}{N}}" 2>/dev/null)" = "Y" ]; then
		covered=$((covered + 1))
		continue
	fi
	if [ "$(exim -be "\${if match_ip{$probe}{$probe}{Y}{N}}" 2>/dev/null)" != "Y" ]; then
		echo "seed_skiprbl_extra: dropping unparsable entry: $addr" >&2
		bad=$((bad + 1))
		continue
	fi

	note=$(echo "$note" | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//')
	if [ -n "$note" ]; then
		printf '%s  # %s\n' "$addr" "$note" >> "$KEEP"
	else
		printf '%s\n' "$addr" >> "$KEEP"
	fi
	kept=$((kept + 1))
done < "$LIVE"

"$SQLITE" -init /dev/null -batch "$DB" <<SQL
INSERT INTO settings (name, value, updated_at)
VALUES ('skiprbl-extra', CAST(readfile('$KEEP') AS TEXT), datetime('now'))
ON CONFLICT(name) DO UPDATE SET value = excluded.value, updated_at = datetime('now');
SQL
rc=$?
if [ $rc -ne 0 ]; then
	echo "seed_skiprbl_extra: could not store the extra addresses" >&2
	exit 1
fi

echo "seed_skiprbl_extra: kept $kept operator address(es), $covered already covered by a provider, $bad unparsable"

"$BUILDER" --quiet || true
exit 0
