#!/bin/bash
# Install mail-client autoconfiguration (Thunderbird / Outlook) on this server.
#
# WHAT IT IS
# Thunderbird 115+ asks https://<domain>/.well-known/autoconfig/mail/config-v1.1.xml
# for the mail settings of the address being added (the "mail/" segment is part
# of the spec). That rides the account's existing vhost and certificate, so
# unlike the older autoconfig.<domain> route it needs no extra DNS record and no
# extra certificate. Outlook asks /autodiscover/autodiscover.xml.
#
# Nothing in either answer varies per request -- %EMAILADDRESS% is a placeholder
# the client substitutes itself -- so the answers are static files generated by
# scripts/update_autoconfig into /var/lib/reqad/autoconfig/ and served directly
# by the web server. There is no PHP in the request path.
#
# WHAT THIS SCRIPT DOES
#   1. creates /var/lib/reqad/autoconfig
#   2. writes /etc/nginx/reqad-autoconfig.conf (the shared location snippet)
#   3. writes /etc/httpd/conf.d/reqad-autoconfig.conf when httpd is installed
#   4. backfills the include / Alias lines into vhosts that predate the feature
#   5. generates the files and reloads the web server
#
# Safe to run repeatedly.

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

AC_DIR=/var/lib/reqad/autoconfig
NGINX_SNIPPET=/etc/nginx/reqad-autoconfig.conf
NGINX_CONF_DIR=/etc/nginx/conf.d
HTTPD_CONF_DIR=/etc/httpd/conf.d

echo "== Mail client autoconfiguration =="

# ---------------------------------------------------------------- 1. storage
mkdir -p "$AC_DIR"
chown root:root "$AC_DIR"
chmod 755 "$AC_DIR"
echo "  Directory: $AC_DIR"

# ------------------------------------------------------------ 2. nginx snippet
# Owned by the panel and regenerated here, so it is written unconditionally.
cat > "$NGINX_SNIPPET" <<'EOF'
# Reqad — mail client autoconfiguration.
# Include this inside the :443 server block of every hosted vhost.
#
# The files are generated by /usr/local/reqad/scripts/update_autoconfig; nothing
# in them varies per request, so there is no PHP in the request path. A domain
# with no file 404s on purpose — that is what makes Thunderbird fall through to
# the ISPDB, the right answer for a web-only account whose MX is elsewhere.
#
# $host in the path is safe: nginx validates the Host header itself and answers
# 400 to anything that is not a plain hostname, so nothing can escape the
# directory.

# Thunderbird 115+ probes exactly one lowercase path, so an exact-match location
# is used: it is decided before nginx evaluates any regex location, and it
# cannot be shadowed by the vhost's own rules — in particular the
# "location ~ /\. { deny all; }" that would otherwise 403 the .well-known path.
location = /.well-known/autoconfig/mail/config-v1.1.xml {
    alias         /var/lib/reqad/autoconfig/$host.xml;
    default_type  text/xml;
    add_header    Cache-Control "public, max-age=3600";
    access_log    off;
}

# Outlook and other Exchange-style clients. Case-insensitive regex rather than
# an exact match because the capitalisation of this path varies by client
# (/autodiscover/autodiscover.xml and /Autodiscover/Autodiscover.xml are both
# sent in the wild).
#
# Outlook POSTs here, and nginx's static file handler answers 405 to POST, so
# the 405 is turned back into the file. Note that Outlook queries
# autodiscover.<domain> before the domain root — this only catches the clients
# that fall back to the root.
location ~* ^/autodiscover/autodiscover\.xml$ {
    alias         /var/lib/reqad/autoconfig/$host.autodiscover.xml;
    default_type  text/xml;
    error_page    405 =200 $uri;
    add_header    Cache-Control "public, max-age=3600";
    access_log    off;
}
EOF
chmod 644 "$NGINX_SNIPPET"
echo "  Snippet:   $NGINX_SNIPPET"

# ------------------------------------------------------------ 3. apache grant
if [ -d "$HTTPD_CONF_DIR" ]; then
    cat > "$HTTPD_CONF_DIR/reqad-autoconfig.conf" <<'EOF'
# Reqad — mail client autoconfiguration (Thunderbird / Outlook).
#
# Apache has no Host variable usable in Alias, so — unlike the single nginx
# snippet, which keys off $host — the Alias lines carry the domain and live in
# each vhost (see scripts/templates/apache-ssl.conf). This file grants access to
# the directory they point at, which is required: the stock
# /etc/httpd/conf/httpd.conf denies everything under / by default, so without
# this block every request answers 403 instead of serving the file.
#
# Verified behaviour, which differs from nginx in one useful way:
#   * POST to the aliased file answers 200 — Apache's default handler serves it,
#     so Outlook needs no equivalent of nginx's "error_page 405 =200 $uri".
#   * A domain with no generated file answers 404, which is what makes
#     Thunderbird fall through to the ISPDB.
#   * Alias maps the URL outside DocumentRoot, so a customer's .htaccess (a
#     WordPress rewrite, say) cannot intercept these paths.
<Directory "/var/lib/reqad/autoconfig">
    Require all granted
    Options None
    AllowOverride None
</Directory>
EOF
    chmod 644 "$HTTPD_CONF_DIR/reqad-autoconfig.conf"
    echo "  Snippet:   $HTTPD_CONF_DIR/reqad-autoconfig.conf"
fi

# --------------------------------------------------------- 4. backfill vhosts
# Every vhost touched below is copied here first, so a bad edit can be undone
# wholesale if the config test fails.
BACKUP=/var/lib/reqad/autoconfig-vhost-backup-$(date +%Y%m%d%H%M%S)

restore_backup() {
    [ -d "$BACKUP" ] || return
    for f in "$BACKUP"/*; do
        [ -f "$f" ] || continue
        target=$(head -1 "$f" | sed -n 's|^#REQAD-ORIG: ||p')
        [ -n "$target" ] || continue
        tail -n +2 "$f" > "$target"
    done
    echo "  Restored the original vhosts from $BACKUP."
}

backup_conf() {
    mkdir -p "$BACKUP"
    { echo "#REQAD-ORIG: $1"; cat "$1"; } > "$BACKUP/$(echo "$1" | tr '/' '_')"
}

nginx_changed=0
if [ -d "$NGINX_CONF_DIR" ]; then
    for conf in "$NGINX_CONF_DIR"/*.conf; do
        [ -f "$conf" ] || continue
        grep -q "server_name" "$conf" 2>/dev/null || continue
        grep -q "reqad-autoconfig.conf" "$conf" 2>/dev/null && continue
        grep -q "listen 443" "$conf" 2>/dev/null || continue

        backup_conf "$conf"

        # Add the include immediately after the "root" line of the :443 block,
        # which is where the template puts it. Only the first match is touched.
        awk '
            /listen 443/ { in443=1 }
            in443 && !done && /^[ \t]*root[ \t]/ {
                print
                print "    # Mail client autoconfiguration (Thunderbird / Outlook)."
                print "    include /etc/nginx/reqad-autoconfig.conf;"
                done=1
                next
            }
            { print }
        ' "$conf" > "$conf.tmp" && mv "$conf.tmp" "$conf"

        if grep -q "reqad-autoconfig.conf" "$conf"; then
            echo "  Updated:   $(basename "$conf")"
            nginx_changed=$((nginx_changed + 1))
        else
            echo "  SKIPPED:   $(basename "$conf") (no root directive in the :443 block)"
        fi
    done
fi

httpd_changed=0
if [ -d "$HTTPD_CONF_DIR" ]; then
    for conf in "$HTTPD_CONF_DIR"/*.conf; do
        [ -f "$conf" ] || continue
        case "$(basename "$conf")" in reqad-autoconfig.conf) continue ;; esac
        grep -q "ServerName" "$conf" 2>/dev/null || continue
        grep -q "/var/lib/reqad/autoconfig/" "$conf" 2>/dev/null && continue

        domain=$(basename "$conf" .conf)
        case "$domain" in *.*) ;; *) continue ;; esac

        backup_conf "$conf"

        awk -v d="$domain" '
            /VirtualHost .*:443/ { in443=1 }
            in443 && !done && /Include \/etc\/letsencrypt\/options-ssl-apache.conf/ {
                print "    # Mail client autoconfiguration (Thunderbird / Outlook)."
                print "    Alias /.well-known/autoconfig/mail/config-v1.1.xml /var/lib/reqad/autoconfig/" d ".xml"
                print "    AliasMatch (?i)^/autodiscover/autodiscover\\.xml$ /var/lib/reqad/autoconfig/" d ".autodiscover.xml"
                print ""
                done=1
            }
            { print }
        ' "$conf" > "$conf.tmp" && mv "$conf.tmp" "$conf"

        if grep -q "/var/lib/reqad/autoconfig/" "$conf"; then
            echo "  Updated:   $(basename "$conf")"
            httpd_changed=$((httpd_changed + 1))
        else
            echo "  SKIPPED:   $(basename "$conf") (no options-ssl-apache.conf anchor)"
        fi
    done
fi

# ------------------------------------------------------- 5. generate + reload
if [ -x /usr/local/reqad/scripts/update_autoconfig ]; then
    /usr/local/reqad/scripts/update_autoconfig
fi

if command -v nginx >/dev/null 2>&1 && systemctl is-active --quiet nginx; then
    if nginx -t >/dev/null 2>&1; then
        systemctl reload nginx
        echo "  nginx reloaded ($nginx_changed vhost(s) updated)."
    else
        echo "  ERROR: nginx config test failed after the backfill — rolling back."
        restore_backup
        nginx -t || echo "  nginx -t still fails; the problem predates this script."
        exit 1
    fi
fi

if command -v httpd >/dev/null 2>&1 && systemctl is-active --quiet httpd; then
    if apachectl configtest >/dev/null 2>&1; then
        systemctl reload httpd
        echo "  httpd reloaded ($httpd_changed vhost(s) updated)."
    else
        echo "  ERROR: httpd config test failed after the backfill — rolling back."
        restore_backup
        apachectl configtest || echo "  configtest still fails; the problem predates this script."
        exit 1
    fi
fi

echo "Done."
